# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

clone_depth: 10

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: >-
      if ($env:nodejs_version -eq "0.10") {
        npm -g install npm@2
        $env:PATH="$env:APPDATA\npm;$env:PATH"
      }
  - npm install

build: off

test_script:
  - node --version && npm --version
  - npm test

matrix:
  fast_finish: true

cache:
  - '%APPDATA%\npm\node_modules -> package.json'    # global npm modules
  - 'node_modules -> package.json'                  # local npm modules
